name: Wget Website Mirror to Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to mirror (required)'
        required: true
        default: 'https://example.com'
      release_tag:
        description: 'Release tag (e.g., v1.0.0 or latest)'
        required: true
        default: 'latest'

jobs:
  mirror-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup 7z
        run: sudo apt-get update && sudo apt-get install -y p7zip-full
        
      - name: Mirror website with wget
        run: |
          wget -r -p -np -k --restrict-file-names=nocontrol "${{ github.event.inputs.url }}"
        
      - name: Identify mirrored directory
        id: find_dir
        run: |
          # Find the top-level directory created by wget (usually the domain name)
          DIR=$(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path "." | head -n 1 | xargs basename)
          echo "mirrored_dir=$DIR" >> $GITHUB_OUTPUT
          echo "Mirrored directory: $DIR"
        
      - name: Compress to 7z
        run: |
          7z a -t7z website-mirror.7z "${{ steps.find_dir.outputs.mirrored_dir }}/"
        
      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: Website Mirror for ${{ github.event.inputs.url }}
          body: |
            Automated mirror of ${{ github.event.inputs.url }}
            Created at $(date -u +"%Y-%m-%d %H:%M:%S UTC")
            Mirrored directory: ${{ steps.find_dir.outputs.mirrored_dir }}
          files: website-mirror.7z
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}