name: clone site

on:
  workflow_dispatch:
      inputs:
        URL:
             required: true
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: do the work
        run: |
          set -ex
          echo "### setting up git repo and pushing change... ###"
          pwd
          ls -lhA
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "${{ secrets.SITECOPY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "ci@github.io"
          git config --global user.name "ci"
          
          
          echo "### cloning website ... ###"
          #sudo apt install -y wget 
          #wget --mirror --convert-links --adjust-extension --page-requisites --no-parent $(tail -n1 urls.txt|cut -d " " -f1) >res.txt
          sudo apt update -y
          sudo apt install -y wget
          mkdir ${{github.event.inputs.URL}}
          cd ${{github.event.inputs.URL}}
          wget -r -p -np -k –restrict-file-names=nocontrol ${{github.event.inputs.URL}}
          echo "### cloning website done ###"
          echo "### push changes ###"
          
          
          git add -A
          git commit -m "update  site" --allow-empty
          git push
          rm -rf ~/.ssh/          
