name: Website Mirror

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to mirror (required)'
        required: true
        default: 'https://example.com'
      target_dir:
        description: 'Target directory for mirrored website'
        required: false
        default: 'mirrored_site'

jobs:
  mirror-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create target directory
        run: mkdir -p "${{ github.event.inputs.target_dir }}"
        
      - name: Mirror website with wget
        run: |
          wget -r -p -np -k --restrict-file-names=nocontrol \
            -P "${{ github.event.inputs.target_dir }}" \
            "${{ github.event.inputs.url }}"
        
      - name: Archive mirrored site
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mirrored-website
          path: ${{ github.event.inputs.target_dir }}